# Generated by Django 5.0.6 on 2024-08-31 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCage",
            fields=[
                (
                    "cagemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.cagemodel",
                    ),
                ),
            ],
            options={
                "db_table": "stockcage",
                "managed": True,
            },
            bases=("common.cagemodel",),
        ),
    ]
