name: Build and Test

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list
    
    #- name: Install Chrome
      #run: |
        #sudo apt-get update
        #sudo apt-get install -y google-chrome-stable
        
   # - name: Configure Chrome options
      #run: |
        #google-chrome --version
        #chromedriver --version
        #python <<EOF
        #from selenium import webdriver
        #from selenium.webdriver.chrome.options import Options
        #chrome_options = Options()
        #chrome_options.add_argument('--no-sandbox')
        #chrome_options.add_argument('--disable-dev-shm-usage')
        #chrome_options.add_argument('--headless')
        #driver = webdriver.Chrome(options=chrome_options)
        #driver.quit()
        #EOF

    - name: Test main app
      run: python manage.py test main
               
    - name: Test breeding_cage app
      run: python manage.py test breeding_cage

    - name: Test mice_repository app
      run: python manage.py test mice_repository

    - name: Test mice_requests app
      run: python manage.py test mice_requests

    - name: Test projects app
      run: python manage.py test projects

    - name: Test stock_cage app
      run: python manage.py test stock_cage

    - name: Test strain app
      run: python manage.py test strain

    - name: Test system_users app
      run: python manage.py test system_users    

    - name: Test wean_pups app
      run: python manage.py test wean_pups

    - name: Test website app
      run: python manage.py test website